services:
  ulinkshortener:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ulinkshortener
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./.env:/app/.env