name: Update Bun Lockfile

on:
  pull_request:
    paths:
      - 'package.json'

jobs:
  fix-lockfile:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'dependabot/')
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: oven-sh/setup-bun@v1
      - name: Install and update lockfile
        run: |
          bun install
      - name: Commit and push updated lockfile
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add bun.lock
          git commit -m "chore: update lockfile (auto-fix for Dependabot PR)" || exit 0
          git push